# Generated by Django 4.1.7 on 2023-05-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('News', 'News'), ('Blog', 'Blog')], max_length=100)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('title_2', models.CharField(max_length=100)),
                ('quote', models.CharField(blank=True, max_length=100, null=True)),
                ('description_2', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='blog_images')),
                ('image_2', models.ImageField(upload_to='blog_images')),
                ('image_3', models.ImageField(upload_to='blog_images')),
                ('title_3', models.CharField(max_length=100)),
                ('description_3', models.CharField(max_length=100)),
                ('title_4', models.CharField(max_length=100)),
                ('description_4', models.CharField(max_length=100)),
            ],
        ),
    ]
