# Generated by Django 4.1.7 on 2023-05-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('News', 'News'), ('Blog', 'Blog')], max_length=100)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='blog_images')),
            ],
            options={
                'verbose_name': 'Добавить пост или новость',
                'verbose_name_plural': 'Добавить посты или новости',
            },
        ),
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('title_2', models.CharField(max_length=255)),
                ('quote', models.CharField(blank=True, max_length=255, null=True)),
                ('description_2', models.TextField()),
                ('image', models.ImageField(upload_to='blog_images')),
                ('image_2', models.ImageField(upload_to='blog_images')),
                ('image_3', models.ImageField(upload_to='blog_images')),
                ('title_3', models.CharField(max_length=255)),
                ('description_3', models.TextField()),
                ('title_4', models.CharField(max_length=100)),
                ('description_4', models.TextField()),
                ('title_5', models.CharField(max_length=100)),
                ('description_5', models.TextField()),
            ],
            options={
                'verbose_name': 'Добавить контент к посту или к новости',
                'verbose_name_plural': 'Добавить контент к постам или к новостям',
            },
        ),
    ]
