# Generated by Django 4.1.7 on 2023-05-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_and_news', '0003_remove_body_main_title_alter_body_description_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='body',
            name='description_5',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='body',
            name='title_5',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
