# Generated by Django 4.1.7 on 2023-05-11 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_and_news', '0004_body_description_5_body_title_5'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='BlogNews',
        ),
    ]
