# Generated by Django 4.1.7 on 2023-05-11 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_and_news', '0005_rename_blog_blognews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blognews',
            options={'verbose_name': 'Добавить пост или новость', 'verbose_name_plural': 'Добавить посты или новости'},
        ),
        migrations.AlterModelOptions(
            name='body',
            options={'verbose_name': 'Добавить контент к посту или к новости', 'verbose_name_plural': 'Добавить контент к постам или к новостям'},
        ),
    ]
