# Generated by Django 4.1.7 on 2023-07-19 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_and_news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slides', models.ImageField(upload_to='slides_images', verbose_name='Изображение')),
                ('blogs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='blog_and_news.blognews', verbose_name='Блог новостей')),
            ],
            options={
                'verbose_name': 'Добавить слайд',
                'verbose_name_plural': 'Добавить слайды',
                'db_table': 'slides',
            },
        ),
    ]
