# Generated by Django 4.1.7 on 2023-05-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TourAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tour_time', models.CharField(max_length=100)),
                ('number_of_people', models.IntegerField()),
                ('price', models.IntegerField()),
                ('when_is_tour', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media/static/images/tour_images')),
            ],
            options={
                'verbose_name': 'Добавление тура',
                'verbose_name_plural': 'Добавления туров',
                'ordering': ['-when_is_tour'],
            },
        ),
    ]
