# Generated by Django 4.1.7 on 2023-05-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='touradd',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='media/static/images/tour_images'),
        ),
        migrations.AddField(
            model_name='touradd',
            name='image_3',
            field=models.ImageField(default=0, upload_to='media/static/images/tour_images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='touradd',
            name='image_4',
            field=models.ImageField(default=1, upload_to='media/static/images/tour_images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='touradd',
            name='image_5',
            field=models.ImageField(default=1, upload_to='media/static/images/tour_images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='touradd',
            name='image_6',
            field=models.ImageField(default=1, upload_to='media/static/images/tour_images'),
            preserve_default=False,
        ),
    ]
