# Generated by Django 4.1.7 on 2023-05-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_touradd_image_2_touradd_image_3_touradd_image_4_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how_day', models.IntegerField()),
                ('path_to_tour', models.CharField(max_length=100)),
                ('location_first', models.CharField(max_length=100)),
                ('hours_from_car', models.CharField(max_length=100)),
                ('location_second', models.CharField(max_length=100)),
                ('hours_from_horse', models.CharField(max_length=100)),
                ('location_third', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='touradd',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='media/static/images/tour_images'),
        ),
        migrations.AlterField(
            model_name='touradd',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='media/static/images/tour_images'),
        ),
        migrations.AlterField(
            model_name='touradd',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='media/static/images/tour_images'),
        ),
        migrations.AlterField(
            model_name='touradd',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='media/static/images/tour_images'),
        ),
        migrations.AlterField(
            model_name='touradd',
            name='image_6',
            field=models.ImageField(blank=True, null=True, upload_to='media/static/images/tour_images'),
        ),
    ]
