# Generated by Django 4.1.7 on 2023-05-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_tourprogram_alter_touradd_image_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_includes', models.CharField(max_length=100)),
                ('price_includes_2', models.CharField(blank=True, max_length=100, null=True)),
                ('price_includes_3', models.CharField(blank=True, max_length=100, null=True)),
                ('price_includes_4', models.CharField(blank=True, max_length=100, null=True)),
                ('price_includes_5', models.CharField(blank=True, max_length=100, null=True)),
                ('price_includes_6', models.CharField(blank=True, max_length=100, null=True)),
                ('price_includes_7', models.CharField(blank=True, max_length=100, null=True)),
                ('price_includes_8', models.CharField(blank=True, max_length=100, null=True)),
                ('price_includes_9', models.CharField(blank=True, max_length=100, null=True)),
                ('price_includes_10', models.CharField(blank=True, max_length=100, null=True)),
                ('price_not_includes', models.CharField(max_length=100)),
                ('price_not_includes_2', models.CharField(blank=True, max_length=100, null=True)),
                ('price_not_includes_3', models.CharField(blank=True, max_length=100, null=True)),
                ('price_not_includes_4', models.CharField(blank=True, max_length=100, null=True)),
                ('price_not_includes_5', models.CharField(blank=True, max_length=100, null=True)),
                ('price_not_includes_6', models.CharField(blank=True, max_length=100, null=True)),
                ('price_not_includes_7', models.CharField(blank=True, max_length=100, null=True)),
                ('price_not_includes_8', models.CharField(blank=True, max_length=100, null=True)),
                ('price_not_includes_9', models.CharField(blank=True, max_length=100, null=True)),
                ('price_not_includes_10', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
