# Generated by Django 4.1.7 on 2023-05-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=100)),
                ('what_to_bring', models.CharField(max_length=100)),
                ('what_to_bring_2', models.CharField(blank=True, max_length=100, null=True)),
                ('what_to_bring_3', models.CharField(blank=True, max_length=100, null=True)),
                ('what_to_bring_4', models.CharField(blank=True, max_length=100, null=True)),
                ('what_to_bring_5', models.CharField(blank=True, max_length=100, null=True)),
                ('what_to_bring_6', models.CharField(blank=True, max_length=100, null=True)),
                ('what_to_bring_7', models.CharField(blank=True, max_length=100, null=True)),
                ('what_to_bring_8', models.CharField(blank=True, max_length=100, null=True)),
                ('what_to_bring_9', models.CharField(blank=True, max_length=100, null=True)),
                ('what_to_bring_10', models.CharField(blank=True, max_length=100, null=True)),
                ('what_to_bring_11', models.CharField(blank=True, max_length=100, null=True)),
                ('what_to_bring_12', models.CharField(blank=True, max_length=100, null=True)),
                ('what_to_bring_13', models.CharField(blank=True, max_length=100, null=True)),
                ('what_to_bring_14', models.CharField(blank=True, max_length=100, null=True)),
                ('what_to_bring_15', models.CharField(blank=True, max_length=100, null=True)),
                ('tittle_2', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
