# Generated by Django 4.1.7 on 2023-05-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0005_tips'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/static/images/tour_images/Photo')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='media/static/images/tour_images/Photo')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='media/static/images/tour_images/Photo')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='media/static/images/tour_images/Photo')),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='media/static/images/tour_images/Photo')),
                ('image_6', models.ImageField(blank=True, null=True, upload_to='media/static/images/tour_images/Photo')),
                ('image_7', models.ImageField(blank=True, null=True, upload_to='media/static/images/tour_images/Photo')),
                ('image_8', models.ImageField(blank=True, null=True, upload_to='media/static/images/tour_images/Photo')),
                ('image_9', models.ImageField(blank=True, null=True, upload_to='media/static/images/tour_images/Photo')),
                ('image_10', models.ImageField(blank=True, null=True, upload_to='media/static/images/tour_images/Photo')),
            ],
        ),
    ]
