# Generated by Django 4.1.7 on 2023-05-05 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/images', verbose_name='Изображение')),
                ('image_two', models.ImageField(upload_to='static/images', verbose_name='Изображение 2')),
                ('image_three', models.ImageField(upload_to='static/images', verbose_name='Изображение 3')),
                ('image_four', models.ImageField(upload_to='static/images', verbose_name='Изображение 4')),
            ],
            options={
                'verbose_name': 'Прикрепить изображение',
                'verbose_name_plural': 'Прикрепить изображения',
                'ordering': ['-image'],
                'unique_together': {('image',)},
            },
        ),
        migrations.CreateModel(
            name='CommentName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Имя пользователя',
            },
        ),
        migrations.CreateModel(
            name='CommentStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=0, verbose_name='Оценка тура')),
            ],
            options={
                'verbose_name': 'Оценка туров',
                'verbose_name_plural': 'Оценки туров',
            },
        ),
        migrations.CreateModel(
            name='CommentText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'отзывы',
            },
        ),
        migrations.CreateModel(
            name='FormQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Ваш email')),
                ('message', models.TextField(blank=True, null=True, verbose_name='вопрос')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы c формы главной страницы',
            },
        ),
        migrations.CreateModel(
            name='FormBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Ваш email')),
                ('whatsapp', models.CharField(blank=True, max_length=100, null=True, verbose_name='Whatsapp(необязательно)')),
                ('date', models.DateTimeField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Бронирование тура',
                'verbose_name_plural': 'Бронирование туров',
                'ordering': ['-date'],
                'unique_together': {('name', 'email')},
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('image', models.ImageField(upload_to='static/images_blog', verbose_name='Прикрепить изображение')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Опубликовать пост',
                'verbose_name_plural': 'Опубликовать посты',
                'unique_together': {('id',)},
            },
        ),
        migrations.CreateModel(
            name='CommentView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Изображение', to='client_actions.commentimage', verbose_name='Изображение\n(необязательно)')),
                ('image_four', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_four_related', to='client_actions.commentimage', verbose_name='Изображение 4(необязательно)')),
                ('image_three', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_three_related', to='client_actions.commentimage', verbose_name='Изображение 3(необязательно)')),
                ('image_two', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_two_related', to='client_actions.commentimage', verbose_name='Изображение 2(необязательно)')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_actions.commentname', verbose_name='Имя пользователя')),
                ('stars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_actions.commentstar', verbose_name='Оценка тура(1-10)')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_actions.commenttext', verbose_name='ваш отзыв')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-date'],
                'unique_together': {('name',)},
            },
        ),
    ]
