# Generated by Django 4.1.7 on 2023-05-05 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_actions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentview',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Изображение', to='client_actions.commentimage', verbose_name='Изображение\n(необязательно)'),
        ),
    ]
