# Generated by Django 4.1.7 on 2023-06-06 10:13

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TourAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tour_time', models.CharField(max_length=100)),
                ('number_of_people', models.IntegerField()),
                ('price', models.IntegerField()),
                ('when_is_tour', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='tour_images')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='tour_images')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='tour_images')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='tour_images')),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='tour_images')),
                ('image_6', models.ImageField(blank=True, null=True, upload_to='tour_images')),
            ],
            options={
                'verbose_name': 'Добавление тура',
                'verbose_name_plural': 'Добавления туров',
                'ordering': ['-when_is_tour'],
            },
        ),
        migrations.CreateModel(
            name='TourProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how_day', models.IntegerField(verbose_name='номер дня')),
                ('location_first', models.CharField(max_length=100, verbose_name='Первая локация')),
                ('first_transport_duration', models.CharField(max_length=100, verbose_name='Длительность первой поездки')),
                ('first_transport_type', models.CharField(choices=[('1', 'Машина'), ('3', 'Лошадь'), ('2', 'Пешком')], max_length=100, verbose_name='Тип траспорта')),
                ('location_second', models.CharField(max_length=100, verbose_name='Вторая локация')),
                ('second_transport_duration', models.CharField(max_length=100, verbose_name='Длительность второй поездки')),
                ('second_transport_type', models.CharField(choices=[('1', 'Машина'), ('3', 'Лошадь'), ('2', 'Пешком')], max_length=100, verbose_name='Тип транспорта')),
                ('location_third', models.CharField(max_length=100, verbose_name='Третья локация')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='tour.touradd', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Программа тура',
                'verbose_name_plural': 'Программы туров',
                'ordering': ['-how_day'],
            },
        ),
        migrations.CreateModel(
            name='TourDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.CharField(max_length=100, null=True, verbose_name='Дата от: ')),
                ('date_up_to', models.CharField(max_length=100, null=True, verbose_name='Дата до: ')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='tour.touradd', verbose_name='Туры')),
            ],
            options={
                'verbose_name': 'Добавить дату тура',
                'verbose_name_plural': 'Добавить дату тура',
            },
        ),
        migrations.CreateModel(
            name='Tips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('what_to_bring', models.CharField(max_length=100, verbose_name='Список')),
                ('what_to_bring_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Список')),
                ('what_to_bring_3', models.CharField(blank=True, max_length=100, null=True, verbose_name='Список')),
                ('what_to_bring_4', models.CharField(blank=True, max_length=100, null=True, verbose_name='Список')),
                ('what_to_bring_5', models.CharField(blank=True, max_length=100, null=True, verbose_name='Список')),
                ('what_to_bring_6', models.CharField(blank=True, max_length=100, null=True, verbose_name='Список')),
                ('what_to_bring_7', models.CharField(blank=True, max_length=100, null=True, verbose_name='Список')),
                ('what_to_bring_8', models.CharField(blank=True, max_length=100, null=True, verbose_name='Список')),
                ('what_to_bring_9', models.CharField(blank=True, max_length=100, null=True, verbose_name='Список')),
                ('what_to_bring_10', models.CharField(blank=True, max_length=100, null=True, verbose_name='Список')),
                ('what_to_bring_11', models.CharField(blank=True, max_length=100, null=True, verbose_name='Список')),
                ('what_to_bring_12', models.CharField(blank=True, max_length=100, null=True, verbose_name='Список')),
                ('what_to_bring_13', models.CharField(blank=True, max_length=100, null=True, verbose_name='Список')),
                ('what_to_bring_14', models.CharField(blank=True, max_length=100, null=True, verbose_name='Список')),
                ('what_to_bring_15', models.CharField(blank=True, max_length=100, null=True, verbose_name='Список')),
                ('tittle_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок 2')),
                ('description', models.TextField(verbose_name='Описание')),
                ('tour', models.OneToOneField(on_delete=django.db.models.expressions.Case, related_name='tips', to='tour.touradd', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Совет',
                'verbose_name_plural': 'Советы',
            },
        ),
        migrations.CreateModel(
            name='PriceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.IntegerField(blank=True, null=True, verbose_name='Количество человек: ')),
                ('in_com', models.IntegerField(blank=True, null=True, verbose_name='Общая цена: ')),
                ('per_person', models.IntegerField(blank=True, null=True, verbose_name='Цена за одного человека: ')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_details', to='tour.touradd', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Цена: ',
                'verbose_name_plural': 'Цены: ',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_includes', models.CharField(max_length=100)),
                ('price_includes_2', models.CharField(blank=True, max_length=100, null=True)),
                ('price_includes_3', models.CharField(blank=True, max_length=100, null=True)),
                ('price_includes_4', models.CharField(blank=True, max_length=100, null=True)),
                ('price_includes_5', models.CharField(blank=True, max_length=100, null=True)),
                ('price_includes_6', models.CharField(blank=True, max_length=100, null=True)),
                ('price_includes_7', models.CharField(blank=True, max_length=100, null=True)),
                ('price_includes_8', models.CharField(blank=True, max_length=100, null=True)),
                ('price_includes_9', models.CharField(blank=True, max_length=100, null=True)),
                ('price_includes_10', models.CharField(blank=True, max_length=100, null=True)),
                ('price_not_includes', models.CharField(max_length=100)),
                ('price_not_includes_2', models.CharField(blank=True, max_length=100, null=True)),
                ('price_not_includes_3', models.CharField(blank=True, max_length=100, null=True)),
                ('price_not_includes_4', models.CharField(blank=True, max_length=100, null=True)),
                ('price_not_includes_5', models.CharField(blank=True, max_length=100, null=True)),
                ('price_not_includes_6', models.CharField(blank=True, max_length=100, null=True)),
                ('price_not_includes_7', models.CharField(blank=True, max_length=100, null=True)),
                ('price_not_includes_8', models.CharField(blank=True, max_length=100, null=True)),
                ('price_not_includes_9', models.CharField(blank=True, max_length=100, null=True)),
                ('price_not_includes_10', models.CharField(blank=True, max_length=100, null=True)),
                ('tour', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='tour.touradd', verbose_name='Ценовые включения')),
            ],
            options={
                'verbose_name': 'Что входит в стоимость и не входит в стоимость',
                'verbose_name_plural': 'Что входит в стоимость и не входит в стоимость',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/static/images/tour_images/Photo', verbose_name='Добавить фото(обязательно)')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='media/static/images/tour_images/Photo', verbose_name='Добавить фото(не обязательно)')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='media/static/images/tour_images/Photo', verbose_name='Добавить фото(не обязательно)')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='media/static/images/tour_images/Photo', verbose_name='Добавить фото(не обязательно)')),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='media/static/images/tour_images/Photo', verbose_name='Добавить фото(не обязательно)')),
                ('image_6', models.ImageField(blank=True, null=True, upload_to='media/static/images/tour_images/Photo', verbose_name='Добавить фото(не обязательно)')),
                ('image_7', models.ImageField(blank=True, null=True, upload_to='media/static/images/tour_images/Photo', verbose_name='Добавить фото(не обязательно)')),
                ('image_8', models.ImageField(blank=True, null=True, upload_to='media/static/images/tour_images/Photo', verbose_name='Добавить фото(не обязательно)')),
                ('image_9', models.ImageField(blank=True, null=True, upload_to='media/static/images/tour_images/Photo', verbose_name='Добавить фото(не обязательно)')),
                ('image_10', models.ImageField(blank=True, null=True, upload_to='media/static/images/tour_images/Photo', verbose_name='Добавить фото(не обязательно)')),
                ('tour', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='tour.touradd', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Добавить фото',
                'verbose_name_plural': 'Добавить фото',
            },
        ),
        migrations.CreateModel(
            name='BookingPrivateTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Имя: ')),
                ('email_or_whatsapp', models.CharField(max_length=100, null=True, verbose_name='Контакты: ')),
                ('date', models.DateTimeField(verbose_name='Дата от: ')),
                ('date_up_to', models.DateTimeField(verbose_name='Дата до: ')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_bookings', to='tour.touradd')),
            ],
            options={
                'verbose_name': 'Бронирование приватного тура',
                'verbose_name_plural': 'Бронирование приватных туров',
            },
        ),
        migrations.CreateModel(
            name='BookingGroupTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Имя: ')),
                ('email_or_whatsapp', models.CharField(max_length=100, null=True, verbose_name='Контакты: ')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_bookings', to='tour.tourdates')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_bookings', to='tour.touradd')),
            ],
            options={
                'verbose_name': 'Бронирование группового тура',
                'verbose_name_plural': 'Бронирование групповых туров',
            },
        ),
    ]
