# Generated by Django 4.1.7 on 2023-07-19 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PhotoComment',
            new_name='Photo',
        ),
        migrations.RenameModel(
            old_name='PriceDetails',
            new_name='PriceDetail',
        ),
        migrations.AlterModelOptions(
            name='tourprogram',
            options={'verbose_name': 'Программа тура', 'verbose_name_plural': 'Программы туров'},
        ),
        migrations.RemoveField(
            model_name='price',
            name='price_includes_10',
        ),
        migrations.RemoveField(
            model_name='price',
            name='price_includes_2',
        ),
        migrations.RemoveField(
            model_name='price',
            name='price_includes_3',
        ),
        migrations.RemoveField(
            model_name='price',
            name='price_includes_4',
        ),
        migrations.RemoveField(
            model_name='price',
            name='price_includes_5',
        ),
        migrations.RemoveField(
            model_name='price',
            name='price_includes_6',
        ),
        migrations.RemoveField(
            model_name='price',
            name='price_includes_7',
        ),
        migrations.RemoveField(
            model_name='price',
            name='price_includes_8',
        ),
        migrations.RemoveField(
            model_name='price',
            name='price_includes_9',
        ),
        migrations.RemoveField(
            model_name='price',
            name='price_not_includes_10',
        ),
        migrations.RemoveField(
            model_name='price',
            name='price_not_includes_2',
        ),
        migrations.RemoveField(
            model_name='price',
            name='price_not_includes_3',
        ),
        migrations.RemoveField(
            model_name='price',
            name='price_not_includes_4',
        ),
        migrations.RemoveField(
            model_name='price',
            name='price_not_includes_5',
        ),
        migrations.RemoveField(
            model_name='price',
            name='price_not_includes_6',
        ),
        migrations.RemoveField(
            model_name='price',
            name='price_not_includes_7',
        ),
        migrations.RemoveField(
            model_name='price',
            name='price_not_includes_8',
        ),
        migrations.RemoveField(
            model_name='price',
            name='price_not_includes_9',
        ),
        migrations.RemoveField(
            model_name='tips',
            name='what_to_bring_10',
        ),
        migrations.RemoveField(
            model_name='tips',
            name='what_to_bring_11',
        ),
        migrations.RemoveField(
            model_name='tips',
            name='what_to_bring_12',
        ),
        migrations.RemoveField(
            model_name='tips',
            name='what_to_bring_13',
        ),
        migrations.RemoveField(
            model_name='tips',
            name='what_to_bring_14',
        ),
        migrations.RemoveField(
            model_name='tips',
            name='what_to_bring_15',
        ),
        migrations.RemoveField(
            model_name='tips',
            name='what_to_bring_2',
        ),
        migrations.RemoveField(
            model_name='tips',
            name='what_to_bring_3',
        ),
        migrations.RemoveField(
            model_name='tips',
            name='what_to_bring_4',
        ),
        migrations.RemoveField(
            model_name='tips',
            name='what_to_bring_5',
        ),
        migrations.RemoveField(
            model_name='tips',
            name='what_to_bring_6',
        ),
        migrations.RemoveField(
            model_name='tips',
            name='what_to_bring_7',
        ),
        migrations.RemoveField(
            model_name='tips',
            name='what_to_bring_8',
        ),
        migrations.RemoveField(
            model_name='tips',
            name='what_to_bring_9',
        ),
        migrations.RemoveField(
            model_name='tourprogram',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tourprogram',
            name='first_transport_duration',
        ),
        migrations.RemoveField(
            model_name='tourprogram',
            name='first_transport_type',
        ),
        migrations.RemoveField(
            model_name='tourprogram',
            name='how_day',
        ),
        migrations.RemoveField(
            model_name='tourprogram',
            name='location_first',
        ),
        migrations.RemoveField(
            model_name='tourprogram',
            name='location_second',
        ),
        migrations.RemoveField(
            model_name='tourprogram',
            name='location_third',
        ),
        migrations.RemoveField(
            model_name='tourprogram',
            name='second_transport_duration',
        ),
        migrations.RemoveField(
            model_name='tourprogram',
            name='second_transport_type',
        ),
        migrations.AddField(
            model_name='touradd',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='touradd',
            name='tour_program',
            field=models.ManyToManyField(blank=True, null=True, related_name='tour_program', to='tour.tourprogram', verbose_name='Программа тура'),
        ),
        migrations.AddField(
            model_name='touradd',
            name='type',
            field=models.CharField(max_length=100, null=True, verbose_name='Тип тура'),
        ),
        migrations.AlterField(
            model_name='tips',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tips',
            name='tittle_2',
            field=models.CharField(max_length=100, verbose_name='Заголовок 2'),
        ),
        migrations.AlterField(
            model_name='tips',
            name='what_to_bring',
            field=models.CharField(max_length=1800, verbose_name='Список'),
        ),
        migrations.AlterField(
            model_name='tourprogram',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.touradd'),
        ),
        migrations.CreateModel(
            name='TourProgramDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how_day', models.IntegerField(verbose_name='номер дня')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.touradd')),
            ],
            options={
                'verbose_name': 'Программа тура',
                'verbose_name_plural': 'Программы туров',
                'ordering': ['-how_day'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_location', models.CharField(max_length=100, verbose_name='Локация')),
                ('type', models.CharField(choices=[('1', 'Место'), ('2', 'Питание'), ('3', 'Ночлег')], default='1', max_length=100, verbose_name='Тип локации')),
                ('description_location', models.TextField(blank=True, max_length=100, null=True, verbose_name='Описание')),
                ('time', models.CharField(max_length=100, verbose_name='Время поездки')),
                ('type_of_transport', models.CharField(choices=[('car', 'car'), ('horse', 'horse'), ('on foot', 'on foot'), ('Пешком', 'Пешком'), ('На машине', 'На машине'), ('Верхом', 'Верхом')], max_length=100, verbose_name='тип транспорта')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.touradd', verbose_name='Тур')),
                ('tour_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='tour.tourprogram')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
            },
        ),
        migrations.AddField(
            model_name='tourprogram',
            name='day_list',
            field=models.ManyToManyField(related_name='adekvatniy_name', to='tour.tourprogramday'),
        ),
    ]
