# Generated by Django 4.1.7 on 2023-07-19 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_rename_photocomment_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourprogramday',
            name='locations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tour.location'),
        ),
    ]
