# Generated by Django 4.1.7 on 2023-07-20 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_tourprogramday_locations'),
    ]

    operations = [
        migrations.CreateModel(
            name='NextTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Пешком', 'Walk'), ('Лошадь', 'Horse'), ('Машина', 'Car')], max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='location',
            name='type_of_transport',
        ),
        migrations.AlterField(
            model_name='location',
            name='type',
            field=models.CharField(choices=[('Место', 'Location'), ('Питание', 'Food'), ('Ночлег', 'Sleep')], default='Место', max_length=100, verbose_name='Тип локации'),
        ),
        migrations.RemoveField(
            model_name='tourprogramday',
            name='locations',
        ),
        migrations.AddField(
            model_name='location',
            name='nextTransport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tour.nexttransport'),
        ),
        migrations.AddField(
            model_name='tourprogramday',
            name='locations',
            field=models.ManyToManyField(blank=True, null=True, to='tour.location'),
        ),
    ]
