# Generated by Django 4.1.7 on 2023-07-19 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxi',
            name='map',
            field=models.ImageField(blank=True, null=True, upload_to='taxi_map_to_path', verbose_name='Карта пути таксиста'),
        ),
    ]
