# Generated by Django 4.1.7 on 2023-06-06 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=0, verbose_name='Оценка тура')),
                ('name', models.CharField(max_length=100)),
                ('text', models.TextField(verbose_name='ваш отзыв')),
                ('image', models.ImageField(upload_to='static/images', verbose_name='Изображение')),
                ('image_two', models.ImageField(blank=True, null=True, upload_to='static/images', verbose_name='Изображение 2(необязательно)')),
                ('image_three', models.ImageField(blank=True, null=True, upload_to='static/images', verbose_name='Изображение 3(необязательно)')),
                ('image_four', models.ImageField(blank=True, null=True, upload_to='static/images', verbose_name='Изображение 4(необязательно)')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('is_approved', models.BooleanField(default=False)),
                ('at_moderation', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.touradd', verbose_name='выбрать тур')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-date'],
            },
        ),
    ]
