# Generated by Django 4.1.7 on 2023-07-19 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_actions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentview',
            name='image',
        ),
        migrations.RemoveField(
            model_name='commentview',
            name='image_four',
        ),
        migrations.RemoveField(
            model_name='commentview',
            name='image_three',
        ),
        migrations.RemoveField(
            model_name='commentview',
            name='image_two',
        ),
        migrations.AlterField(
            model_name='commentview',
            name='stars',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0, verbose_name='Оценка тура'),
        ),
        migrations.CreateModel(
            name='PhotoComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='comment_photos', verbose_name='фото')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='client_actions.commentview')),
            ],
            options={
                'verbose_name': 'Фотография комментария',
                'verbose_name_plural': 'Фотографии комментарии',
            },
        ),
    ]
