# Generated by Django 4.1.7 on 2023-05-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarRental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_rental_slider')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='car_rental_slider')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='car_rental_slider')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='car_rental_slider')),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='car_rental_slider')),
                ('image_6', models.ImageField(blank=True, null=True, upload_to='car_rental_slider')),
                ('image_7', models.ImageField(blank=True, null=True, upload_to='car_rental_slider')),
                ('image_8', models.ImageField(blank=True, null=True, upload_to='car_rental_slider')),
                ('image_9', models.ImageField(blank=True, null=True, upload_to='car_rental_slider')),
                ('image_10', models.ImageField(blank=True, null=True, upload_to='car_rental_slider')),
                ('name_car', models.CharField(max_length=100, verbose_name='Наименование машины')),
                ('status', models.CharField(choices=[('Available', 'Available'), ('unavailable', 'unavailable')], max_length=100, verbose_name='Статус машины')),
                ('capacity', models.IntegerField(verbose_name='Вместимость машины')),
                ('transmission', models.CharField(max_length=100, verbose_name='Коробка передач')),
                ('steering_wheel', models.CharField(max_length=100, verbose_name='Руль')),
                ('type_of_fuel', models.CharField(max_length=100, verbose_name='Тип топлива')),
                ('Type_of_drive', models.CharField(max_length=100, verbose_name='Тип привода')),
                ('engine_capacity', models.IntegerField(verbose_name='Мощность двигателя')),
                ('power', models.CharField(max_length=100, verbose_name='Скорость')),
                ('configuration', models.CharField(max_length=100, verbose_name='Конфигурация машины')),
                ('consumption', models.CharField(max_length=100, verbose_name='Расход')),
                ('per_kilometer', models.IntegerField(verbose_name='за километр')),
                ('driver_comfort', models.IntegerField(verbose_name='Питание и проживание водителя на 1 день')),
                ('how_days_driving', models.IntegerField(verbose_name='Количество дней езды без водителя')),
                ('how_days_driving_without_driver', models.IntegerField(verbose_name='Количество дней езды без водителя')),
                ('how_days_driving_without_driver_2', models.IntegerField(verbose_name='Количество дней езды без водителя')),
                ('how_days_driving_without_driver_3', models.IntegerField(verbose_name='Количество дней езды без водителя')),
            ],
        ),
    ]
