# Generated by Django 4.1.7 on 2023-05-13 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taxi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_of_departure', models.CharField(max_length=100, verbose_name='Место отъезда')),
                ('place_of_arrival', models.CharField(max_length=100, verbose_name='Место приема')),
                ('name_taxi', models.CharField(max_length=100, verbose_name='Тип такси')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('how_hours', models.IntegerField(verbose_name='Количество часов')),
            ],
        ),
    ]
