# Generated by Django 4.1.7 on 2023-05-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_taxi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxi',
            name='how_hours',
            field=models.CharField(max_length=40, verbose_name='Количество часов'),
        ),
    ]
